{
 "title": "NIDS Dashboard - Vigilix Kafka Monitoring",
 "tags": [
  "IDS",
  "Vigilix",
  "Prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "📈 Total Network Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "vigilix_kafka_requests_total" }
   ]
  },
  {
   "title": "🚨 Total Anomalies Detected",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "vigilix_kafka_anomalies_total" }
   ]
  },
  {
   "title": "⚠️ Anomaly Ratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "vigilix_kafka_anomaly_ratio" }
   ]
  },
  {
   "title": "Model Accuracy",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vigilix_model_accuracy * 100" }
   ]
  },
  {
   "title": "Model Precision",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vigilix_model_precision * 100" }
   ]
  },
  {
   "title": "Model Recall",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vigilix_model_recall * 100" }
   ]
  },
  {
   "title": "Model F1-Score",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vigilix_model_f1 * 100" }
   ]
  },
  {
   "title": "📊 Requests Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "rate(vigilix_kafka_requests_total[1m])"
    }
   ]
  },
  {
   "title": "📊 Anomalies Over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(vigilix_kafka_anomalies_total[1m])"
    }
   ]
  }
 ]
}