import unittest
import requests

class TestCICIDSModel(unittest.TestCase):
    API_URL = "http://localhost:5000/predict"  # Update to your actual endpoint

    def setUp(self):
        # Define a list of test cases based on CIC-IDS attack categories and benign flows
        self.test_cases = [
    {
        "name": "CIC-IDS2017 DDoS Attack Sample",
        "payload": {
            "features": {
                "Flow Duration": 39000000.0,
                "Total Fwd Packets": 9.0,
                "Total Backward Packets": 3.0,
                "Fwd Packets Length Total": 54.0,
                "Bwd Packets Length Total": 18.0,
                "Fwd Packet Length Max": 6.0,
                "Fwd Packet Length Mean": 6.0,
                "Fwd Packet Length Std": 0.0,
                "Bwd Packet Length Max": 6.0,
                "Bwd Packet Length Mean": 6.0,
                "Bwd Packet Length Std": 0.0,
                "Flow Bytes/s": 1.3,
                "Flow Packets/s": 0.3,
                "Flow IAT Mean": 4300000.0,
                "Flow IAT Std": 6000000.0,
                "Flow IAT Max": 15000000.0,
                "Flow IAT Min": 0.0,
                "Fwd IAT Total": 39000000.0,
                "Fwd IAT Mean": 4880000.0,
                "Fwd IAT Std": 7000000.0,
                "Fwd IAT Max": 15000000.0,
                "Fwd IAT Min": 0.0,
                "Bwd IAT Total": 1.0,
                "Bwd IAT Mean": 1.0,
                "Bwd IAT Std": 0.0,
                "Bwd IAT Max": 1.0,
                "Bwd IAT Min": 1.0,
                "Fwd PSH Flags": 0.0,
                "Fwd Header Length": 180.0,
                "Bwd Header Length": 40.0,
                "Fwd Packets/s": 0.25,
                "Bwd Packets/s": 0.05,
                "Packet Length Max": 6.0,
                "Packet Length Mean": 6.0,
                "Packet Length Std": 0.0,
                "Packet Length Variance": 0.0,
                "SYN Flag Count": 0.0,
                "URG Flag Count": 0.0,
                "Avg Packet Size": 6.6,
                "Avg Fwd Segment Size": 6.0,
                "Avg Bwd Segment Size": 6.0,
                "Subflow Fwd Packets": 9.0,
                "Subflow Fwd Bytes": 54.0,
                "Subflow Bwd Packets": 3.0,
                "Subflow Bwd Bytes": 18.0,
                "Init Fwd Win Bytes": 5840.0,
                "Init Bwd Win Bytes": 0.0,
                "Fwd Act Data Packets": 8.0,
                "Fwd Seg Size Min": 20.0,
                "Active Mean": 64.0,
                "Active Std": 0.0,
                "Active Max": 64.0,
                "Active Min": 64.0,
                "Idle Mean": 12500000.0,
                "Idle Std": 1600000.0,
                "Idle Max": 14900000.0,
                "Idle Min": 10000000.0
            }
        },
        "expected_prediction": 1,
        "expected_status": "attack"
    },
    {
        "name": "CIC-IDS2017 Benign Traffic Sample",
        "payload": {
            "features": {
                "Flow Duration": 15000000.0,
                "Total Fwd Packets": 5.0,
                "Total Backward Packets": 5.0,
                "Fwd Packets Length Total": 150.0,
                "Bwd Packets Length Total": 150.0,
                "Fwd Packet Length Max": 30.0,
                "Fwd Packet Length Mean": 30.0,
                "Fwd Packet Length Std": 0.0,
                "Bwd Packet Length Max": 30.0,
                "Bwd Packet Length Mean": 30.0,
                "Bwd Packet Length Std": 0.0,
                "Flow Bytes/s": 20.0,
                "Flow Packets/s": 0.66,
                "Flow IAT Mean": 3000000.0,
                "Flow IAT Std": 500000.0,
                "Flow IAT Max": 5000000.0,
                "Flow IAT Min": 1000000.0,
                "Fwd IAT Total": 15000000.0,
                "Fwd IAT Mean": 3000000.0,
                "Fwd IAT Std": 400000.0,
                "Fwd IAT Max": 4500000.0,
                "Fwd IAT Min": 1500000.0,
                "Bwd IAT Total": 14000000.0,
                "Bwd IAT Mean": 2800000.0,
                "Bwd IAT Std": 300000.0,
                "Bwd IAT Max": 4000000.0,
                "Bwd IAT Min": 1000000.0,
                "Fwd PSH Flags": 1.0,
                "Fwd Header Length": 100.0,
                "Bwd Header Length": 100.0,
                "Fwd Packets/s": 0.33,
                "Bwd Packets/s": 0.33,
                "Packet Length Max": 30.0,
                "Packet Length Mean": 30.0,
                "Packet Length Std": 0.0,
                "Packet Length Variance": 0.0,
                "SYN Flag Count": 1.0,
                "URG Flag Count": 0.0,
                "Avg Packet Size": 30.0,
                "Avg Fwd Segment Size": 30.0,
                "Avg Bwd Segment Size": 30.0,
                "Subflow Fwd Packets": 5.0,
                "Subflow Fwd Bytes": 150.0,
                "Subflow Bwd Packets": 5.0,
                "Subflow Bwd Bytes": 150.0,
                "Init Fwd Win Bytes": 8192.0,
                "Init Bwd Win Bytes": 8192.0,
                "Fwd Act Data Packets": 5.0,
                "Fwd Seg Size Min": 40.0,
                "Active Mean": 30.0,
                "Active Std": 5.0,
                "Active Max": 40.0,
                "Active Min": 20.0,
                "Idle Mean": 5000000.0,
                "Idle Std": 1000000.0,
                "Idle Max": 6000000.0,
                "Idle Min": 4000000.0
            }
        },
        "expected_prediction": 0,
        "expected_status": "benign"
    },
    {
        "name": "CIC-IDS2017 Port Scan Attack",
        "payload": {
            "features": {
                "Flow Duration": 12000000.0,
                "Total Fwd Packets": 10.0,
                "Total Backward Packets": 0.0,
                "Fwd Packets Length Total": 60.0,
                "Bwd Packets Length Total": 0.0,
                "Fwd Packet Length Max": 6.0,
                "Fwd Packet Length Mean": 6.0,
                "Fwd Packet Length Std": 0.0,
                "Bwd Packet Length Max": 0.0,
                "Bwd Packet Length Mean": 0.0,
                "Bwd Packet Length Std": 0.0,
                "Flow Bytes/s": 5.0,
                "Flow Packets/s": 0.8,
                "Flow IAT Mean": 1000000.0,
                "Flow IAT Std": 200000.0,
                "Flow IAT Max": 2000000.0,
                "Flow IAT Min": 500000.0,
                "Fwd IAT Total": 12000000.0,
                "Fwd IAT Mean": 1200000.0,
                "Fwd IAT Std": 250000.0,
                "Fwd IAT Max": 2000000.0,
                "Fwd IAT Min": 500000.0,
                "Bwd IAT Total": 0.0,
                "Bwd IAT Mean": 0.0,
                "Bwd IAT Std": 0.0,
                "Bwd IAT Max": 0.0,
                "Bwd IAT Min": 0.0,
                "Fwd PSH Flags": 1.0,
                "Fwd Header Length": 120.0,
                "Bwd Header Length": 0.0,
                "Fwd Packets/s": 0.83,
                "Bwd Packets/s": 0.0,
                "Packet Length Max": 6.0,
                "Packet Length Mean": 6.0,
                "Packet Length Std": 0.0,
                "Packet Length Variance": 0.0,
                "SYN Flag Count": 1.0,
                "URG Flag Count": 0.0,
                "Avg Packet Size": 6.0,
                "Avg Fwd Segment Size": 6.0,
                "Avg Bwd Segment Size": 0.0,
                "Subflow Fwd Packets": 10.0,
                "Subflow Fwd Bytes": 60.0,
                "Subflow Bwd Packets": 0.0,
                "Subflow Bwd Bytes": 0.0,
                "Init Fwd Win Bytes": 8192.0,
                "Init Bwd Win Bytes": 0.0,
                "Fwd Act Data Packets": 9.0,
                "Fwd Seg Size Min": 20.0,
                "Active Mean": 40.0,
                "Active Std": 5.0,
                "Active Max": 50.0,
                "Active Min": 30.0,
                "Idle Mean": 3000000.0,
                "Idle Std": 500000.0,
                "Idle Max": 4000000.0,
                "Idle Min": 2000000.0
            }
        },
        "expected_prediction": 1,
        "expected_status": "attack"
    },
    {
        "name": "CIC-IDS2018 Brute Force Attack",
        "payload": {
            "features": {
                "Flow Duration": 80000000.0,
                "Total Fwd Packets": 100.0,
                "Total Backward Packets": 100.0,
                "Fwd Packets Length Total": 6000.0,
                "Bwd Packets Length Total": 6000.0,
                "Fwd Packet Length Max": 60.0,
                "Fwd Packet Length Mean": 60.0,
                "Fwd Packet Length Std": 0.0,
                "Bwd Packet Length Max": 60.0,
                "Bwd Packet Length Mean": 60.0,
                "Bwd Packet Length Std": 0.0,
                "Flow Bytes/s": 150.0,
                "Flow Packets/s": 2.5,
                "Flow IAT Mean": 300000.0,
                "Flow IAT Std": 100000.0,
                "Flow IAT Max": 1000000.0,
                "Flow IAT Min": 100000.0,
                "Fwd IAT Total": 40000000.0,
                "Fwd IAT Mean": 400000.0,
                "Fwd IAT Std": 150000.0,
                "Fwd IAT Max": 1200000.0,
                "Fwd IAT Min": 100000.0,
                "Bwd IAT Total": 40000000.0,
                "Bwd IAT Mean": 400000.0,
                "Bwd IAT Std": 150000.0,
                "Bwd IAT Max": 1200000.0,
                "Bwd IAT Min": 100000.0,
                "Fwd PSH Flags": 5.0,
                "Fwd Header Length": 2000.0,
                "Bwd Header Length": 2000.0,
                "Fwd Packets/s": 1.25,
                "Bwd Packets/s": 1.25,
                "Packet Length Max": 60.0,
                "Packet Length Mean": 60.0,
                "Packet Length Std": 0.0,
                "Packet Length Variance": 0.0,
                "SYN Flag Count": 30.0,
                "URG Flag Count": 0.0,
                "Avg Packet Size": 60.0,
                "Avg Fwd Segment Size": 60.0,
                "Avg Bwd Segment Size": 60.0,
                "Subflow Fwd Packets": 100.0,
                "Subflow Fwd Bytes": 6000.0,
                "Subflow Bwd Packets": 100.0,
                "Subflow Bwd Bytes": 6000.0,
                "Init Fwd Win Bytes": 65535.0,
                "Init Bwd Win Bytes": 65535.0,
                "Fwd Act Data Packets": 95.0,
                "Fwd Seg Size Min": 40.0,
                "Active Mean": 150.0,
                "Active Std": 10.0,
                "Active Max": 160.0,
                "Active Min": 140.0,
                "Idle Mean": 1000000.0,
                "Idle Std": 200000.0,
                "Idle Max": 1300000.0,
                "Idle Min": 800000.0
            }
        },
        "expected_prediction": 1,
        "expected_status": "attack"
    },
    {
        "name": "CIC-IDS2017 Benign Traffic Sample 2",
        "payload": {
            "features": {
                "Flow Duration": 20000000.0,
                "Total Fwd Packets": 7.0,
                "Total Backward Packets": 7.0,
                "Fwd Packets Length Total": 210.0,
                "Bwd Packets Length Total": 210.0,
                "Fwd Packet Length Max": 30.0,
                "Fwd Packet Length Mean": 30.0,
                "Fwd Packet Length Std": 0.0,
                "Bwd Packet Length Max": 30.0,
                "Bwd Packet Length Mean": 30.0,
                "Bwd Packet Length Std": 0.0,
                "Flow Bytes/s": 18.0,
                "Flow Packets/s": 0.7,
                "Flow IAT Mean": 2800000.0,
                "Flow IAT Std": 400000.0,
                "Flow IAT Max": 5000000.0,
                "Flow IAT Min": 1500000.0,
                "Fwd IAT Total": 20000000.0,
                "Fwd IAT Mean": 2850000.0,
                "Fwd IAT Std": 350000.0,
                "Fwd IAT Max": 4500000.0,
                "Fwd IAT Min": 1700000.0,
                "Bwd IAT Total": 19000000.0,
                "Bwd IAT Mean": 2700000.0,
                "Bwd IAT Std": 300000.0,
                "Bwd IAT Max": 4000000.0,
                "Bwd IAT Min": 1500000.0,
                "Fwd PSH Flags": 1.0,
                "Fwd Header Length": 110.0,
                "Bwd Header Length": 110.0,
                "Fwd Packets/s": 0.35,
                "Bwd Packets/s": 0.35,
                "Packet Length Max": 30.0,
                "Packet Length Mean": 30.0,
                "Packet Length Std": 0.0,
                "Packet Length Variance": 0.0,
                "SYN Flag Count": 1.0,
                "URG Flag Count": 0.0,
                "Avg Packet Size": 30.0,
                "Avg Fwd Segment Size": 30.0,
                "Avg Bwd Segment Size": 30.0,
                "Subflow Fwd Packets": 7.0,
                "Subflow Fwd Bytes": 210.0,
                "Subflow Bwd Packets": 7.0,
                "Subflow Bwd Bytes": 210.0,
                "Init Fwd Win Bytes": 8192.0,
                "Init Bwd Win Bytes": 8192.0,
                "Fwd Act Data Packets": 7.0,
                "Fwd Seg Size Min": 35.0,
                "Active Mean": 35.0,
                "Active Std": 4.0,
                "Active Max": 42.0,
                "Active Min": 28.0,
                "Idle Mean": 4500000.0,
                "Idle Std": 900000.0,
                "Idle Max": 5400000.0,
                "Idle Min": 3500000.0
            }
        },
        "expected_prediction": 0,
        "expected_status": "benign"
    }

    # Add more test cases here if needed
    
]

    def test_cic_ids_flows(self):
        for case in self.test_cases:
            with self.subTest(name=case["name"]):
                response = requests.post(self.API_URL, json=case["payload"])
                self.assertEqual(response.status_code, 200, f"Failed API call for {case['name']}")

                result = response.json()
                self.assertIn("prediction", result, f"Missing prediction key in response for {case['name']}")
                self.assertIn("status", result, f"Missing status key in response for {case['name']}")
                self.assertIn("confidence", result, f"Missing confidence key in response for {case['name']}")

                self.assertEqual(result["prediction"], case["expected_prediction"], f"Wrong prediction for {case['name']}")
                self.assertEqual(result["status"], case["expected_status"], f"Wrong status for {case['name']}")
                self.assertGreaterEqual(result["confidence"], 0.9, f"Low confidence for {case['name']}")

                print(f"✔ {case['name']} -> Prediction: {result['prediction']}, Confidence: {result['confidence']:.2f}")

if __name__ == "__main__":
    unittest.main()
